2024-12-27 11:56:22.904040 | Column 'email' cannot be null
2024-12-27 11:57:43.221260 | Column 'email' cannot be null
2025-01-24 10:33:34.038641 | statement (9) doesn't match the number of data elements (8).
2025-01-24 10:34:58.660873 | Data type 'tuple' in column 0 not supported in MariaDB Connector/Python
2025-01-24 10:35:55.546770 | Data type 'tuple' in column 0 not supported in MariaDB Connector/Python
2025-01-24 10:37:04.646410 | Data type 'tuple' in column 0 not supported in MariaDB Connector/Python
2025-02-13 11:22:46.469965 | <class 'dict'> - tipo de la respuesta
2025-02-14 13:12:10.139760 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F05B86FDD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-02-27 19:58:35.654285 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011E86602450>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-19 10:25:23.830762 | Incorrect integer value: '' for column `pki_validacion`.`evidencias_adicionales`.`id_carpeta_entidad` at row 1
2025-03-19 10:25:29.102394 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEC8C8E790>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-19 10:28:47.532428 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEC7C5E4D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-20 09:39:09.138561 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A468B4F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-20 10:18:00.868807 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A006668790>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-20 10:23:53.054530 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000166E087B8D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-21 10:06:11.057583 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F66DF87610>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-21 10:06:31.332962 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F66DFA0310>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-21 10:15:31.685931 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273EFD3B710>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-21 10:15:48.679920 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273EB5C9950>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-03-24 10:20:22.040999 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016DEC75E0D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
2025-04-14 19:04:51.193714 | HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /callback-test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000293E916FF50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')), ha fallado la callback
